packages:
  - packages/*

catalogs:
  content:
    '@nuxt/content': ^3.6.3
    '@shikijs/colorized-brackets': ^3.12.0
    better-sqlite3: ^12.2.0
    nuxt-content-twoslash: ^0.1.2
    plain-shiki: ^0.3.0
    rehype-katex: ^7.0.1
    remark-math: ^6.0.0
    remark-reading-time: ^2.0.2
  framework:
    '@types/node': ^24.3.1
    nuxt: ^4.0.3
    sass-embedded: ^1.91.0
    typescript: ^5.9.2
    vue: ^3.5.20
    vue-router: ^4.5.1
  quality:
    '@antfu/eslint-config': ^5.2.1
    '@nuxt/eslint': ^1.9.0
    '@zinkawaii/stylelint-config': ^0.3.3
    eslint: ^9.34.0
    stylelint: ^16.23.1
  ui:
    '@iconify/json': ^2.2.380
    '@nuxt/icon': ^2.0.0
    '@nuxt/image': ^1.11.0
    '@nuxtjs/color-mode': ^3.5.2
    nuxt-aos: ^1.2.5
    vue-tippy: ^6.7.1
  util:
    '@nuxt/scripts': ^0.11.13
    '@pinia/nuxt': ^0.11.2
    '@vueuse/core': ^13.8.0
    aplayer: ^1.10.1
    ci-info: ^4.3.0
    date-fns: ^4.1.0
    parse-domain: ^8.2.2
    pinia: ^3.0.3
    radash: ^12.1.1
    unplugin-yaml: ^3.0.5

onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - esbuild
  - sharp
  - unrs-resolver

patchedDependencies:
  '@nuxtjs/mdc': patches/@nuxtjs__mdc.patch
  '@vue/shared': patches/@vue__shared.patch
  vue-tippy: patches/vue-tippy.patch

shamefullyHoist: true
catalog:
  lint-staged: ^15.2.9
  simple-git-hooks: ^2.11.1
