const links = [
	{
		name: '推荐',
		description: '都是大佬，推荐关注',
		links: [
			{
				name: '阮一峰',
				logo: 'https://cdn.lightxi.com/cloudreve/uploads/2025/07/31/U0IB1Rq7_person2_s.jpg',
				description: '阮老师，知名博主，大佬中的大佬',
				url: 'https://www.ruanyifeng.com/blog/',
				platform: 'Cloudflare',
			},
			{
				name: 'Antfu',
				url: 'https://antfu.me/',
				logo: 'https://cdn.lightxi.com/cloudreve/uploads/2025/08/02/wQRfFIj8_antfu.svg',
				description: 'Vue 核心成员',
				framework: 'Vue',
				platform: 'Vercel',
			},
		],
	},
	{
		name: '挚交好友',
		description: '这里记录了我的挚交好友',
		links: [
			{
				name: '青桔气球',
				url: 'https://blog.qjqq.cn/',
				logo: 'https://cdn.lightxi.com/cloudreve/uploads/2025/08/02/5l6lLT6c_headimg_dl.jpg',
				description: '分享网络安全与科技生活',
				framework: 'Hexo',
				platform: '国内 CDN',
			},
			{
				name: '爱吃肉的猫',
				url: 'https://meuicat.com/',
				logo: 'https://cdn.lightxi.com/cloudreve/uploads/2025/08/02/rXQ2DErb_662953b6d9923.jpg',
				description: '有肉有猫有生活.',
				framework: 'Hexo',
				platform: '国内 CDN',
			},
			{
				name: 'isYangs',
				url: 'https://isyangs.cn',
				logo: 'https://7.isyangs.cn/8/655c9835780a0-8.jpg',
				description: '一个前端Bug构造师的博客',
				framework: 'Vue',
				platform: 'Vercel',
			},
			{
				name: '纸鹿摸鱼处',
				url: 'https://blog.zhilu.site/',
				logo: 'https://www.zhilu.site/api/avatar.png',
				description: '纸鹿至麓不知路，支炉制露不止漉',
				framework: 'Nuxt',
				platform: 'Vercel',
			},
		],
	},
	{
		name: '小伙伴们',
		description: '这里记录了我的小伙伴们',
		links: [
			{
				name: 'Adil',
				url: 'https://blog.adil.com.cn/',
				logo: 'https://cdn.lightxi.com/cloudreve/uploads/2025/07/31/kDD24XCZ_photo.png',
				description: '专注分享SAP优质内容',
				framework: 'Hexo',
				platform: '国内 CDN',
			},
			{
				name: '周润发',
				url: 'https://blog.zrf.me/',
				logo: 'https://cdn.lightxi.com/cloudreve/uploads/2025/08/02/UpNi3h1B_logo.webp',
				description: '收录开源，好用的互联网项目',
				framework: 'Hexo',
				platform: 'Vercel',
			},
			{
				name: 'Mo的记事簿',
				url: 'https://blog.xiowo.net/',
				logo: 'https://cdn.lightxi.com/cloudreve/uploads/2025/08/03/v59aHZSJ_avatar.jpg',
				description: '万年鸽王，哈哈OvO',
				framework: 'Hexo',
				platform: 'Vercel',
			},
			{
				name: '陆小启',
				url: 'https://blog.zonox.top/',
				logo: 'https://cdn.lightxi.com/cloudreve/uploads/2025/08/05/lGQxfmZC_67d3fbedaa1c6.webp',
				description: '往者不谏，来者可追',
				framework: 'Typecho',
				platform: 'Cloudflare',
			},
			{
				name: 'Frederick\'s Blog',
				url: 'https://blog.ohdragonboi.cn',
				logo: 'https://cdn.lightxi.com/cloudreve/uploads/2025/08/05/7EdEr4TF_dwadwadwadwa.png',
				description: 'Sky is the limit.',
				framework: 'Next.js',
				platform: 'Vercel',
			},
			{
				name: 'Eilo’s Blog',
				url: 'https://www.eilo.uk/',
				logo: 'https://cdn.lightxi.com/cloudreve/uploads/2025/08/05/1kXgsG2h_logo.png',
				description: '等等我记一下',
				framework: 'Hexo',
				platform: '服务器',
			},
			{
				name: '新锐博客',
				url: 'https://www.xrbk.cn/',
				logo: 'https://cdn.lightxi.com/cloudreve/uploads/2025/08/07/pwMbfaRM_favicon.png',
				description: '记录学习与分享教程',
				framework: 'Hexo',
				platform: '国内 CDN',
			},
			{
				name: '❖星港◎Star☆',
				url: 'https://blog.starsharbor.com',
				logo: 'https://cdn.lightxi.com/cloudreve/uploads/2025/08/06/ZuNIstlQ_67f92f6fcfb26.webp',
				description: '以博客记录生活与热爱！',
				framework: 'Hexo',
				platform: 'Netlify',
			},
		],
	},
]

export default links
